name: build-snapd-archlinux
on: push

jobs:
  build-snapd:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/dbz2k/docker-container-builder-archlinux-makepkg:main
    steps:
         - name: Download PKGBUILD
           run: |
                chown -R builduser $HOME &&
                ls -l &&
                sudo -u builduser touch testfie.txt &&
                git clone https://aur.archlinux.org/snapd.git &&
                ls -l
                
         - name: Build package
           run: |
               cd snapd &&
               sudo -u builduser makepkg --syncdeps --noconfirm


           
