name: build-snapd
on: push

jobs:
  build-snapd:
    runs-on: ubuntu-latest
    container:
      image: archlinux:base-devel
    steps:
         - name: Create non-root account
           run: |
                useradd builduser
                passwd -d builduser
         - name: Configure Sudo
           run: |
                pacman -Syu --noconfirm sudo
                printf 'builduser ALL=(ALL) ALL\n' | tee -a /etc/sudoers
     
         - name: Download Dependencies 
           run: |
            pacman -Syu --noconfirm git
         - name: Download PKGBUILD
           run: |
               git clone https://aur.archlinux.org/snapd.git
         - name: Build Package
           run: |
                ls
                chown builuder -R snapd
                sudo -u builduser  makepkg --syncdeps --noconfirm

           
