name: build-snapd-archlinux
on:
  push:
    branches: ['main']
  schedule:
    - cron: '30 8 1,15 * *'


jobs:
  build-snapd:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/dbz2k/docker-container-builder-archlinux-makepkg:nightly
    steps:
         - name: Download PKGBUILD
           run: |
                cd /home/builduser &&
                sudo -u builduser git clone 'https://aur.archlinux.org/snapd.git'
                
         - name: Build package
           run: |
               cd /home/builduser/ &&
               cd snapd &&
               sudo -u builduser makepkg --syncdeps --noconfirm
               
         - name: Release snapd build
           uses: "marvinpinto/action-automatic-releases@latest"
           with:
            repo_token: "${{ secrets.GITHUB_TOKEN }}"
            automatic_release_tag: "latest"
            prerelease: false
            title: "Release snapd build"
            files: |
             /home/builduser/snapd/*.pkg.tar.zst
               


           
