name: build-snapd
on: push

jobs:
  build-snapd:
    runs-on: ubuntu-latest
    container:
      image: archlinux:base-devel
    steps:
         - name: Create non-root account
           run: |
                useradd -m builder
         - name: Configure Sudo
           run: |
                pacman -Syu --noconfirm sudo
                echo "builder ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers
     
         - name: Download Dependencies 
           run: |
            pacman -Syu --noconfirm git
         - name: Download PKGBUILD
           run: |
               cat /etc/passwd
               sudo -u builder
               git clone https://aur.archlinux.org/snapd.git
         - name: Build Package
           run: |
                sudo -u builder
                cd snapd
                makepkg --syncdeps --noconfirm

           
