name: build-snapd-archlinux
on: push

jobs:
  build-snapd:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/dbz2k/docker-container-builder-archlinux-makepkg:main
    steps:
         - name: Download PKGBUILD
           run: |
               sudo -u builduser sudo git clone https://aur.archlinux.org/snapd.git
         - name: Build package
           run: |
               cd snapd
               sudo -u builduser sudo makepkg --syncdeps --noconfirm


           
