name: build-snapd-archlinux
on: push

jobs:
  build-snapd:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/dbz2k/docker-container-builder-archlinux:main
    steps:
         - name: Download dependencies 
           run: |
            sudo pacman -Syu --noconfirm git
         - name: Download PKGBUILD
           run: |
               cd ~/
               git clone https://aur.archlinux.org/snapd.git
         - name: Build package
           run: |
               cd ~/
               cd snapd
               makepkg --syncdeps --noconfirm


           
