name: build-snapd-archlinux
on: push

jobs:
  build-snapd:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/dbz2k/docker-container-builder-archlinux-makepkg:main
    steps:
         - name: Download PKGBUILD
           run: |
                cd /home/builduser &&
                sudo -u builduser git clone 'https://aur.archlinux.org/snapd.git'
                
         - name: Build package
           run: |
               cd /home/builduser/ &&
               cd snapd &&
               sudo -u builduser makepkg --syncdeps --noconfirm &&
               cd /home/builduser/snapd &&
               ls -l
               


           
